### ISSUE TITLE
Create RTMP Local server 

### ISSUE THREAD

**Issue by Goule** [unpause-live/SwiftVideo#29]
Hello,

I'm looking for a way to create RTMP server locally on an iOS app. 

It is possible to do it with this library ? Have you any exemple ? 
I tried to add SwiftVideo with SPM on iOS project but it seems to be broke.

Thanks :)

**Comment by jgh-** [comment]
Hi - sorry for the (very) slow reply. With the new 0.2.0 change I just merged in you can make an RTMP server on iOS.  Follow the build instructions in the README to use with Xcode, and you should be able to use the RTMP example code.

**Comment by Goule** [comment]
Thanks I will try this !!
